baseurl: ""

sass:
    sass_dir: styles
    style: compressed

exclude: [vendor]

collections:
  books:
    output: true
    permalink: /:path/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
      body_class: "default"
      show_navbar: true
      show_footer: true